### ISSUE TITLE
Sample App - "Get Kin" availability depends on current amount of Kin

### ISSUE THREAD

**Issue by Ronserruya** [kinfoundation/kin-sdk-core-ios#47]
Steps to reproduce:

Scenario A:
1. Create a new wallet
2. Send Kin to this wallet

Expected Results: Get Kin button should still be available since the user never used it
Actual Results: If you have more than 0 Kin, the "Get Kin" button becomes disabled

Scenario B:
1. Create a new wallet
2. Tap on Get Kin
3. Empty your account from all Kin (send it to another wallet)

Expected Result: The Get Kin button needs to remain disabled
Actual Result: The Get Kin button becomes available again (Don't know if works, because of #44 )

**Comment by katzio** [comment]
This behavior was revised so the button would work without constraints at all.
